### ISSUE TITLE
subscribing for events and tests

### ISSUE THREAD

**Issue by vbogdanov** [ChaosGroup/json-ws#3]
a.on('testEvent', function(data) {...}); seems to be async operation. A need a way to determine when it is done in order to continue with the test (perform an action that leads to event being emitted).

**Comment by mihail-stanchev** [comment]
It sends an event subscription message to the server, additionally initiates a websocket connection on first use. You can use an event from the server as a notification when the first connection has been made.

**Comment by mihail-stanchev** [comment]
Additionally, we could listen for the newListener event given that we make the actual event subscription once the remote subscription call has finished successfully.
