### ISSUE TITLE
Possible memory leak in WebSocket client proxies.

### ISSUE THREAD

**Issue by psstoev** [ChaosGroup/json-ws#34]
We should investigate the cleaning of callbacks in the WebSocket transport in `client.js`, they seem to leak memory. Check the `send` method in the `WebSocketTransport` prototype.

**Comment by psstoev** [comment]
It turns out that the problem was not there. The problem is that if the the client awaits an answer and the server does not respond, the client leaks callbacks that will never be released. The simplest solution is to regularly clean "Timed out" calls in the WebSocket transport, but we should discuss this further.

**Comment by mihail-stanchev** [comment]
This will be resolved when we implement time-outs.
