### ISSUE TITLE
WebSocket connection failed in dev/2.0 branch

### ISSUE THREAD

**Issue by stoyaneft** [ChaosGroup/json-ws#36]
WebSocket connection to 'ws://localhost:3000/endpoint/pass/test-api/1.0' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

The bug reproduces when initial data is send on line 184 in ws-transport.js.
`ws.send('{}');`

**Comment by psstoev** [comment]
It turned out that the bug is reproducible only on machines running NOD32, so, strangely enough - this is a bug in the antivirus software. More information from people with similar issue here - https://forum.eset.com/topic/8355-protocol-filtering-breaks-websockets-after-update-at-5052016/
